services:
  mongodb:
    image: mongo:7
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - dados-mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dados-mongodb:
